version: "3.9"

services:
  backend:
    build: ./backend
    container_name: taskmanager-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: taskmanager-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped